### ISSUE TITLE
Incorporar tests que muestren que se pueden incluir varios describe en el mismo archivo

### ISSUE THREAD

**Issue by fdodino** [uqbar-project/wollok-language#13]
Según resuelto en https://github.com/uqbar-project/wollok/pull/1765

Debería mostrarse como ejemplo un archivo `.wtest` con varios `describe`

**Comment by npasserini** [comment]
Sería ideal tomar los mismos tests que ya están en xtext, no?

**Comment by fdodino** [comment]
Sí, 
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/xpect/MultipleDescribes.wtest.xt
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/xpect/DuplicatedDescribeTest.wtest.xt

**Comment by nscarcella** [comment]
Relates to #5

**Comment by maurocasciati** [comment]
Already done by @fdodino in [Sanity Test Refactor #22](https://github.com/uqbar-project/wollok-language/pull/22)
