### ISSUE TITLE
Test parameterShouldNotDuplicateExistingVariable no testea caso de herencia

### ISSUE THREAD

**Issue by FerRomMu** [uqbar-project/wollok-language#137]
A raíz de lo charlado acá:
[Issue validación: Error cuando parámetro se llama igual a atributo en wollokTS](https://github.com/uqbar-project/wollok-ts/issues/125)

Y en base a que testeando este comportamiento noté que el Wollok Xtext no lanzaba ni error ni warn en casos de herencia donde el parámetro de un método se llamaba igual que el atributo de una clase padre. Se podría agregar este caso de testeo en el correspondiente test:
https://github.com/uqbar-project/wollok-language/blob/master/test/validations/parameterShouldNotDuplicateExistingVariable.wlk

Por ej algo como lo siguiente al final de tal archivo intuyo que debería ser suficiente para testear este caso:
``` Wollok
class Son inherits Person {

  method repeatedParameters(
    @Expect(code="parameterShouldNotDuplicateExistingVariable", level="error")
    toBeHidden
  ) {}

}
```

**Comment by PalumboN** [comment]
Esto ya está resuelto! 🎉
