### ISSUE TITLE
Agregar a language las descripciones de los errores

### ISSUE THREAD

**Issue by asanzo** [uqbar-project/wollok-language#139]
El lunes nos sentamos a charlar y dijimos que para que todos los proyectos sean felices (lsp-ide, mobile, cli) necesitamos tener las descripciones de errores en 1 sólo lugar. @nscarcella propuso que fueran en wollok-language, y que de paso cañazo estuvieran internacionalizadas en algún formato i18n-friendly.

El laburo sería:

- Crear los archivos en wollok-language con formato i18n (tenemos que decidirlo)
- Hay que decidir cómo utilizar eso desde cada uno de los proyectos. Por ejemplo [en el lsp-ide se usarían acá](https://github.com/uqbar-project/wollok-lsp-ide/blob/5b15b617b948d56e66bf0e6926ab9b58519a7e96/server/src/reporter.ts#L12-L28) y en [wollok mobile acá](https://github.com/uqbar-project/wollok-mobile/tree/dev/translations). 
- En el cli nos gustaría que los stack trace y las validaciones que se impriman por consola tengan esos mensajes.

Cosas que pueden servir para este issue:
- Input: los mensajes de XText [en inglés](https://github.com/uqbar-project/wollok/blob/dev/org.uqbar.project.wollok/src/org/uqbar/project/wollok/messages.properties) y [en español](https://github.com/uqbar-project/wollok/blob/dev/org.uqbar.project.wollok/src/org/uqbar/project/wollok/messages_es.properties)
- El checklist de Dodain [en un google doc](https://docs.google.com/spreadsheets/d/1OPqJEXTufnpD_H2Awenocv8XQbsTqpWVJX8VHv2KPkY/edit#gid=0) donde tiene mapeados los id de validaciones de XText con los de LSP-IDE.

**Comment by asanzo** [comment]
@PalumboN @npasserini @nscarcella @fdodino 

¿Les cierra esto? ¿Algún tip sobre tecnología? ¿Hacemos algo falopa como tenerlo disponible a nivel lenguaje en un errorMessages.translate(key) o es muy sucio?

**Comment by fdodino** [comment]
+1 . Buscando i18n y ts me saltó [este package](https://www.npmjs.com/package/i18n-ts)

**Comment by PalumboN** [comment]
Piolaaa!! 

Ahí completé dónde están las traducciones de Wollok Mobile en la descripción.

> ¿Algún tip sobre tecnología? ¿Hacemos algo falopa como tenerlo disponible a nivel lenguaje en un errorMessages.translate(key) o es muy sucio?

Sobre esto no estoy seguro, podría ser interesante. 

En un principio había pensado simplemente tener los archivos con las traducciones, y que se consuman donde se necesiten.

Pero si quieren hacer algo más cheto, yo veo 2 lugares claves para esto:

- En los [Problems que devuelve el validator](https://github.com/uqbar-project/wollok-ts/blob/master/src/validator.ts#L62-L75): la propuesta actual es pedirle el code y mappear eso a un texto (traducido). Se le podría pedir directamente el mensaje en algún idioma.
- En los [mensajes de las excepciones](https://github.com/uqbar-project/wollok-ts/blob/94f311c92dae84cf39f2c5eff3b692a9353f4fac/src/interpreter/runtimeModel.ts#L41-L53): que ahora no hay forma de traducirlas.

Avisen si necesitan una mano con algo!

**Comment by fdodino** [comment]
Retomo esto, con @PalumboN e @ivojawer acordamos meter un PR con los mensajes del validador en formato JSON.
