### ISSUE TITLE
addVisualCharacter no valida límites de pantalla

### ISSUE THREAD

**Issue by lspigariol** [uqbar-project/wollok-language#182]
Los juegos hechos con wollok xtex asumen que visualCharacter controla que el visual no se salga de la pantalla. 

Solucion propuesta:

```
  method addVisualCharacter(visual) {
    self.addVisual(visual)
    keyboard.up().onPressDo({ 
      if(visual.position().y() < game.height()-1) visual.position(visual.position().up(1)) })
    keyboard.down().onPressDo({ 
      if(visual.position().y() > 0) visual.position(visual.position().down(1)) })
    keyboard.right().onPressDo({ 
      if (visual.position().x() < game.width()-1) visual.position(visual.position().right(1)) })
    keyboard.left().onPressDo({ 
      if (visual.position().x() > 0) visual.position(visual.position().left(1)) })
}

```

**Comment by lspigariol** [comment]
https://github.com/uqbar-project/wollok-language/blob/cb96a7114060ebda634e3fa09038900330cfefa9/src/wollok/game.wlk#L39

**Comment by lspigariol** [comment]
puede ser... por ahora, con que todo lo que andaba siga andando, soy feliz

**Comment by PalumboN** [comment]
> Hay que pensar la interfaz pero yo pensaría en que haya algo como nextPosition(Position) y que vos puedas devolver la misma Position u otra Position...

Hoy en día podés usar el setter de position del objeto para hacer cosas locas.
