### ISSUE TITLE
Nombre de archivo con caracteres inválidos en Windows

### ISSUE THREAD

**Issue by mbertogliati** [uqbar-project/wollok-language#186]
El nombre del archivo [-$!"·$%&( )=|@¢∞¬÷“≠'?.wlk](https://github.com/uqbar-project/wollok-language/blob/master/test/validations/-%24!%22%C2%B7%24%25%26(%20)%3D%7C%40%C2%A2%E2%88%9E%C2%AC%C3%B7%E2%80%9C%E2%89%A0'%3F.wlk) contiene los caracteres `"|?` los cuales no son aceptados en Windows.

No lo son ninguno de los siguientes: `/\:*"?<>|`

Esto lanza un error al clonar el repositorio y el archivo no se copia. Además, rompe con otros repositorios que utilizan este y tienen automatizado el proceso de clonación, como [wollok-cli](https://github.com/uqbar-project/wollok-ts).

```(base) PS C:\Users\HP\Documents\Programacion\wollok> git clone https://github.com/uqbar-project/wollok-language
Cloning into 'wollok-language'...
remote: Enumerating objects: 4009, done.
remote: Counting objects: 100% (1690/1690), done.
remote: Compressing objects: 100% (965/965), done.
remote: Total 4009 (delta 825), reused 1397 (delta 650), pack-reused 2319
Receiving objects: 100% (4009/4009), 838.08 KiB | 3.09 MiB/s, done.
Resolving deltas: 100% (2155/2155), done.
error: unable to create file test/validations/-$!"·$%&( )=|@¢∞¬÷“≠'?.wlk: Invalid argument
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'```

**Comment by PalumboN** [comment]
Buuuu presentía que algo así iba a pasar con ese nombre choto jajaja. Se nota que los principales desarrolladores de Wollok no usamos Windows :P

Propongo renombrarlo simplemente a `invalid-name.wlk` (o si queremos aceptar `-`, que no veo razones fuertes para no hacerlo) `$invalid$name$.wlk`

**Comment by ivojawer** [comment]
Hay una razon por la cual no aceptamos los guines, que es por los imports (https://github.com/uqbar-project/wollok-ts/pull/239#discussion_r1581715784 aca dodine tiro la posta sobre todos estos caracteres 😎)
