### ISSUE TITLE
Al hacer "wollok init" o lanzar la consola REPL en una ruta (de Windows) con carpetas que tienen espacios o caracteres especiales arroja error 

### ISSUE THREAD

**Issue by hernanconiglio** [uqbar-project/wollok-language#192]
Hola! 
Paso a comentar un error que estamos viendo con estudiantes que intentan hacer "wollok init" o ejecutar REPL en una ruta (de windows) con carpetas que tienen espacios o caracteres especiales en su nombre y da error. 
Dejo algunas capturas, cualquier cosa me avisan!
Muchas gracias!

![image](https://github.com/user-attachments/assets/311ab871-e191-4401-815c-9bcd0de23e8f)

![image](https://github.com/user-attachments/assets/068e3f15-5493-4b51-8d78-7e7255accfab)

**Comment by PalumboN** [comment]
@hernanconiglio gracias por reportar.

CREO que entiendo el error en los comandos para ejecutar wollok (`repl`, `run`, etc) porque ellos reciben un path por parámetro, que se está cortando en el espacio (si vez la línea que dice "Initializing Wollok REPL for file ...." ese file está cortado.

No entiendo por qué no funciona con el `init` 🤔  Tendrías algún screenshot del error que tira?

#### Cosas a probar
- Vería si esto se soluciona usando unas comillas. Trataría de lanzar el comando de `wollok repl` a mano pasándole el path del archivo entre comillas, a ver si funca:
```bash
wollok repl "PATH QUE TIENE ESPACIO" -p "PATH A LA BASE DEL PROYECTO"
```

- También habría que probar esto en un NO windows, para ver si también pasa (supongo que sí). Y mismo en Windows con una terminal bash.


### Por ahora

Voy a agregar esto en la página de Troubleshooting que estamos armando https://github.com/uqbar-project/website-wollok-ts/issues/35

**Comment by hernanconiglio** [comment]
Hola @PalumboN !!
Faltó reproducir todos los casos que nos reportaron! 🙃 
El error no aparece al hacer "wollok init" en la terminal, sino en el vscode y hacer click en "Run in REPL", tanto en windows como Linux (Mac no tengo para probar), cuando el proyecto está en una carpeta con las características que describí arriba. Por ejemplo:
Windows 11:
![image](https://github.com/user-attachments/assets/afeedd36-5c80-4bcb-9930-81945ea866fb)

Linux Mint:
![image](https://github.com/user-attachments/assets/418382cd-17c5-4ee4-8ab9-636452969de9)

Gracias!!!

**Comment by PalumboN** [comment]
Ok!! Confirmo que también pasa en Mac y con las comillas se solucionan.

Abrí un issue en LSP para agregarlas cuando le tira el comando a CLI: https://github.com/uqbar-project/wollok-lsp-ide/issues/176

**Comment by hernanconiglio** [comment]
Mchas gracias @PalumboN !  👏 👏 👏

**Comment by PalumboN** [comment]
@hernanconiglio esto ya debería estar solucionado en la nueva versión de la extensión de VSCode https://marketplace.visualstudio.com/items?itemName=uqbar.wollok-lsp-ide

**Comment by hernanconiglio** [comment]
Hola @PalumboN !!
Efectivamente, acabo de revisarlo y ya está resuelto! Muchas gracias!!!
