### ISSUE TITLE
Date.dayOfWeek() -  Corregir Docs

### ISSUE THREAD

**Issue by NicolasKalaydjian** [uqbar-project/wollok-language#194]
El dia de la semana ya no es un WKO como figura en los Docs, ahora es un String
(https://www.wollok.org/documentation/language/#wollok.lang.Date)

https://github.com/uqbar-project/wollok-language/blob/aa06b533a369aecb817b65b3975d1c4fac672dfa/src/wollok/lang.wlk#L2901-L2907

https://github.com/uqbar-project/wollok-language/blob/aa06b533a369aecb817b65b3975d1c4fac672dfa/src/wollok/lang.wlk#L2817-L2830

**Comment by PalumboN** [comment]
La pregunta es si queremos objects o strings, no recuerdo si fue un cambios consensuado.
