### ISSUE TITLE
Wollok Game addVisual requires only positionable but fail if it has no image or image as an empty string ""

### ISSUE THREAD

**Issue by isaiaslafon** [uqbar-project/wollok-language#195]
https://github.com/uqbar-project/wollok-language/blob/master/src/wollok/game.wlk
Line 37
Only require by method documentation a positionable, but if it does not have image methos does not run, if it has image mtehor and return an empty string show "image not found" png at top left of the board but it breaks.
![image break bug](https://github.com/user-attachments/assets/18275306-c9bb-4071-a4c0-4cb4b4a315dd)
No character movement and position not repected (0,0)
![image solved with a proper png](https://github.com/user-attachments/assets/42979d3a-06b8-4e0c-a70d-e732deb2ad7c)

**Comment by PalumboN** [comment]
> but if it does not have image methos does not run

What's the error? It should be an invisible object: https://www.wollok.org/documentation/wollok_game/#objetos-invisibles

**Comment by isaiaslafon** [comment]
It was my mistake, when I try it had a bad path so explodes. Sorry!
