### ISSUE TITLE
Missing Wollok doc for Position classes

### ISSUE THREAD

**Issue by isaiaslafon** [uqbar-project/wollok-language#196]
"Documentaiton not found"
Line 158 >=  (https://github.com/uqbar-project/wollok-site/blob/master/documentacion/wollokdoc/game.html)

Not showing Position and above methods Documentation from:
https://github.com/uqbar-project/wollok-language/blob/master/src/wollok/game.wlk

![image](https://github.com/user-attachments/assets/d517cb10-d9c0-4c5e-ba4b-24c4c49a82e2)

**Comment by fdodino** [comment]
Efectivamente está faltando agregar la documentación con wollok doc.

**Comment by fdodino** [comment]
Acabo de ver que tenemos un issue que contempla este caso: #169 . Cierro éste por duplicado.
