### ISSUE TITLE
Al remover un elemento de una lista, no se muestran correctamente los índices en el gráfico dinámico

### ISSUE THREAD

**Issue by hernanconiglio** [uqbar-project/wollok-language#202]
Hola! 
En la representación gráfica de las listas, al remover un elemento no se renumeran correctaemente los índices.

https://github.com/user-attachments/assets/8efb1c6b-da73-4900-8875-bf521ff6f6da

**Comment by fdodino** [comment]
Hola @hernanconiglio , gracias por reportarlo! El fin de semana nos reportaron un error similar y lo solucionamos, todavía no está releaseado pero próximamente debería arreglarse:

https://github.com/uqbar-project/wollok-web-tools/issues/8

Mantengo el issue abierto hasta que salga el release.

**Comment by hernanconiglio** [comment]
Hola @fdodino ! Muchas gracias!

**Comment by PalumboN** [comment]
Esto ya está arreglado en la v0.2.11 de CLI 👍
