### ISSUE TITLE
Error "Generator is already running" en referencias cíclicas al definir objetos

### ISSUE THREAD

**Issue by julian-berbel** [uqbar-project/wollok-language#222]
El siguiente código tomado de tp grupal llevado a un MRE:
```wollok
class Zona {
  const zonasLimitrofes
}

const edoras = new Zona(zonasLimitrofes = #{bosqueDeFangorn})
const bosqueDeFangorn = new Zona(zonasLimitrofes = #{edoras})
```

Rompe con el mensaje de error "Generator is already running".

<img width="683" alt="image" src="https://github.com/user-attachments/assets/6dd42d0a-1e5e-47ff-aa58-6c990f850b65">

No estoy seguro de si debería estar rompiendo o funcionando, pero en caso de que esté bien que rompa, debería hacerlo con un mensaje de error más fácil de interpretar.

**Comment by PalumboN** [comment]
Esto ya está arreglado en la v0.3.0 🚀
