### ISSUE TITLE
Comportamiento inconsistente entre `map` y `flatMap` para sets

### ISSUE THREAD

**Issue by julian-berbel** [uqbar-project/wollok-language#225]
El método `map` de las colecciones devuelve siempre una lista; tanto para listas como para sets.
El método `flatMap` por el contrario devuelve una colección del mismo tipo que la que recibe el mensaje, lo cual puede llevar a resultados inesperados.

¿Es así adrede? Hubiera esperado que ambos se comportaran de la misma forma y devolvieran siempre una lista.
<img width="948" alt="image" src="https://github.com/user-attachments/assets/36f30868-a2b3-4cdf-b2e9-d64e04ca4874">

**Comment by NicolasKalaydjian** [comment]
![image](https://github.com/user-attachments/assets/9b5b4759-7776-454c-af1b-a68dae9a0421)

![image](https://github.com/user-attachments/assets/08a377ef-d262-43f0-a266-5fdddd9b6326)

Los dos están definidos en Collection, el map usa de semilla para el fold la lista vacía y el flatMap usa una instancia de la coleccion, que puede ser lista o set. Ahí me parece estaría el tema.

**Comment by PalumboN** [comment]
Sí banco que el map y todas sus variantes devuelvan listas. Y el error es donde marca @NicolasKalaydjian !
