### ISSUE TITLE
[Pedido] Collection#map debería lanzar un error si el bloque no retorna un valor

### ISSUE THREAD

**Issue by julian-berbel** [uqbar-project/wollok-language#226]
Creo que esto era una feature en la versión anterior de wollok.
Cuando se usaba map con un bloque que no devolvía un valor solía lanzar un error para desalentar el mal uso de `map` para operaciones con efecto en vez de `forEach`.

**Comment by PalumboN** [comment]
Esto ya debería estar solucionado en el próximo release 🚀

**Comment by PalumboN** [comment]
Esto ya está arreglado en la v0.3.0 🚀
