### ISSUE TITLE
Revisión general de toStrings

### ISSUE THREAD

**Issue by npasserini** [uqbar-project/wollok-language#39]
Hay varios issues relacionados con los toString que me gustaría mirar de forma global y proponer una estrategia. Tal vez sea un cambio grande y haya que pensarlo para Wollok 2.0 (aka Wollok 2020).
- uqbar-project/wollok#1772 ¿Eliminar los atributos del toString?
- uqbar-project/wollok-language#37 El toString de colecciones debería mostrar el toString de los elementos.
- uqbar-project/wollok#1692 Cambiar algunos toStrings de lang, ¿en qué estado está esto?
- Creo que sería importante tener una definición clara de para qué sirven todos los métodos asociados que hoy tenemos y cuál se usa en cada caso: `toString`, `printString`, etc.

Estas definiciones deberían ser globales y parte de la definición de wollok-language.

**Comment by fdodino** [comment]
[Link a la Especificación](https://docs.google.com/document/d/1_cp3tgMSpyqgLF58dxGDmubDc5U3Y3fmGtx4Ezs9hnY/edit#)
