### ISSUE TITLE
Diferenciacion de objetos del dominio y visuales

### ISSUE THREAD

**Issue by lspigariol** [uqbar-project/wollok-language#57]
Hay dos caminos cuando se quiere visualizar en Game un objeto de dominio:
1) agregarle al mismo objeto image/position y la lógica necesaria de movimiento, colisión, etc
2) hacer un objeto nuevo, que actúe como visual del objeto real

a grandes rasgos, el 1 es mas simple el modelo y fácil de manipular y el 2 es mas profesional separando la vista del modelo. (aunque esto último es discutible, dependiendo del dominio: en un juego vista y modelo tienden a confluir) 

hay algunos metodos que quedan a mitad camino, tipo
addVisualIn( ) que requiere que el objeto a mostrar tenga `image`, pero no necesariamente `position`.  (si tiene position, no se lo usa, similar a visualCharacter uqbar-project/wollok#1733 )

Se puede ir hacia un lado y exigir que siempre tengan image y position, o para el otro y hacer un 
addVisulInImage(objeto, position, "image,jpg") para mostrar cualquier objeto sin alterarlo.

despues estan los metodos de Position, como drawElement y drawCharacter (tambien say), que no creo que se usen mucho, , porque son equivalentes a los addVisual,  y se podrian eliminar

**Comment by PalumboN** [comment]
Se eliminaron los métodos en https://github.com/uqbar-project/wollok-language/pull/111
Lo de achicar las primitivas lo veremos más adelante, al mover https://github.com/uqbar-project/wollok-ts/blob/master/src/wre/gameMirror.wlk#L4
