### ISSUE TITLE
Eliminar llamada al constructor desde objetos autodefinidos

### ISSUE THREAD

**Issue by fdodino** [uqbar-project/wollok-language#63]
Tenemos en el inherits de los singletons:

```wollok
object miObjeto inherits MiClase(p1, p2)
```

Si eliminamos los constructores, esa linea debería ser:

```wollok
object miObjeto inherits MiClase(arg1 = p1, arg2 = p2)
```

Relacionado con #53

**Comment by PalumboN** [comment]
@fdodino @nscarcella esto ya está implementado, no?

**Comment by fdodino** [comment]
En Wollok Xtext ya está implementado.

**Comment by nscarcella** [comment]
yup
