### ISSUE TITLE
Renombrar este proyecto a wollok-language

### ISSUE THREAD

**Issue by npasserini** [uqbar-project/wollok-language#7]
Propongo que renombremos este proyecto a wollok-language y se convierta en el concentrador de todas las definiciones del lenguaje Wollok, punto de encuentro entre las especificaciones.

Eventualmente código wollok-sdk se mudaría aquí, posiblemente tendríamos dos carpetas `sdk` y `sanity-tests`. La alternativa es dejar esto como está y crear un wollok-sdk cuando se pueda independizar, pero me parece que tener centralizadas todas las definiciones compartidas puede ser útil. 

@nscarcella @fdodino @PalumboN ¿Qué opinan?

**Comment by fdodino** [comment]
Ya está renombrado. Cierro el issue.
