### ISSUE TITLE
Definir mensaje predeterminado para un nuevo tipo de excepción

### ISSUE THREAD

**Issue by GuidoDipietro** [uqbar-project/wollok-language#78]
Trabajando en un TP de Paradigmas de Programación me encontré con la siguiente situación:

Tenía un modelado de un objeto con cierta función que tenía un caso de excepción, solucionado en clase de la siguiente forma (resumido un poco, y con otros nombres para evitar explicar la temática del TP):

```wollok
class SinCondicionException inherits Exception {}
object algo {
   var algunaCondicion = true
   //..otros metodos
   method metodoExcepcion(){
      if(algunaCondicion)
         throw new SinCondicionException(message="No se cumple la condición.")
      else {  // ... el resto  }
   }
}
```

Sin embargo, cada vez que yo quiero lanzar una excepción de tipo `SinCondicionException`, tengo que definir un nuevo mensaje. Lo ideal sería poder lanzarla así:

```wollok
throw SinCondicionException
```

Al intentar implementar esta solución vimos que no es posible modificar el mensaje dado que está definido como constante:

```wollok
class SinCondicionException inherits Exception {
   override method initialize(){
      message = "No se cumple la condición."
      // Wollok alerta que "no se puede modificar una constante"
   }
}
```

Vimos que en la clase `Exception` el valor de `message` está definido como `const property`, haciendo que esto no pueda modificarse.

Alternativas:
- Cambiar a `var`
- Definir un método que permita inicializar el mensaje predeterminado de una nueva excepción

Un saludo.

**Comment by fdodino** [comment]
Habría que analizar bien el caso de uso, a mí me parece que

- el mensaje debe ser personalizado cuando se construye la excepción. Tener un mensaje "No se cumple la condición" me suena a un smell de un error genérico.
- `throw SinCondicionException` me sigue pareciendo muy genérica: falta indicar el verdadero motivo por el cual no tiene una condición
- e incluso renombraría la clase `SinCondicionException` para ayudar a dar un poco el contexto del ejercicio

En resumen, no estoy muy convencido de que valga la pena hacer ese cambio.

**Comment by GuidoDipietro** [comment]
El nombre de la clase de la excepción y el ejemplo fueron excesivamente genéricos, en el caso real se trataba más bien de algo como "sueldoInsuficienteException" o algo por el estilo.

**Comment by PalumboN** [comment]
Buenas @GuidoDipietro @fdodino , revisando issues caí por acá

> Sin embargo, cada vez que yo quiero lanzar una excepción de tipo `SinCondicionException`, tengo que definir un nuevo mensaje.

Planteo otras alternativas a las que se comentaron:

1. Mover la lógica a otro objeto que se encargue de lanzar esas excepciones:
```Wollok
object validador {
  method validarSueldo(empleado) {
       if(algunaCondicionConEmpleado)
         throw new SinCondicionException(message="No se cumple la condición.")
    // Fijate que a diferencia del código del issue original, no hace falta el `else`, porque corta la ejecución
  }
}
```

2. Sobreescribir el getter y no pasar ningún mensaje:
```Wollok
class SinCondicionException inherits Exception {
   override method message(){
      return "No se cumple la condición."
   }
}
```
La malo de acá es que queda una constante apuntando a basura....

**Comment by PalumboN** [comment]
Buenas! Vuelvo con esto. No sé si antes se podía... pero ahora se puede hacer:

https://github.com/uqbar-project/wollok-language/blob/1f2e1ad4b7e46b04564680349fea077f8898f4e6/test/validations/shouldInitializeInheritedAttributes.wlk#L50

Y para solucionar este issue basta con hacer:
```wollok
class SinCondicionException inherits Exception(message="No se cumple la condición.") { } 
```
