### ISSUE TITLE
¿¿El 2 no es primo??

### ISSUE THREAD

**Issue by GuidoDipietro** [uqbar-project/wollok-language#80]
¡¡Wollok!!
Wollok dice que el número 2 no es primo.

```javascript
1.isPrime() // false, bien
3.isPrime() // true, bien
2.isPrime() // false???????
```

También adjunto una captura porque esto es insólito, yo tampoco lo creí:

![image](https://user-images.githubusercontent.com/48221146/98007344-0938ff00-1dd2-11eb-8aee-a67b5bb03192.png)

**Comment by asanzo** [comment]
JAJAJAJ cualquiera.

**Comment by fdodino** [comment]
primo de quién?
jaja, ok. Lo mandamos a marzo para que aprenda.
