### ISSUE TITLE
Agregar a los tests el assert "esto no debe fallar" (doesNotThrowException)

### ISSUE THREAD

**Issue by asanzo** [uqbar-project/wollok-language#82]
Se desglosa de https://github.com/uqbar-project/wollok/issues/1939 . Para poder cerrar aquél, hay que cerrar este.

Agregar al objeto assert el mensaje para reificar el oráculo tradicionalmente implícito _"si llegué hasta acá sin estallar, el test pasa"_

```Wollok
assert.doesNotThrowException({/*código que no debe estallar*/})
```

El ejemplo de uso que dí allá es:

```Wollok
test "Al transferir desde una cuenta sin guita explota" {
    assert.throwsException({cuenta1.transferir(1000,cuenta2)})
}

test "Al transferir desde una cuenta con guita no explota" {
    cuenta1.depositar(2000)
    assert.doesNotThrowException({cuenta1.transferir(1000,cuenta2)})
}
```

Este feature se vuelve particularmente importante cuando hagamos que fallen los tests sin assert, por eso está linkeado con https://github.com/uqbar-project/wollok/issues/1939.

**Comment by PalumboN** [comment]
Solved
