### ISSUE TITLE
Date sin constructor no pasa nuestras validaciones

### ISSUE THREAD

**Issue by nscarcella** [uqbar-project/wollok-language#99]
Ahora que sacamos los constructores esta definición de Date no permite instanciar la clase sin parámetros:

```wollok
class Date {
  const property day
  const property month
  const property year

  ...
}

const hoy = new Date() // Esto es ilegal, porque day, month y year son consts sin valor default
```

Propongo dos alternativas para arreglar esto:

**Opción 1:** crear un objeto date con un mensaje today:

```wollok
object date {
  method today() native
}

class Date {
  const property day = date.today().day()
  const property month = date.today().month()
  const property year = date.today().year()
  ...
}
```

**Opción 2:** crear directamente un objeto today

```wollok
object today extends Date {
  override method day() native
  override method month() native
  override method year() native
}

class Date {
  const property day = today.day()
  const property month = today.month()
  const property year = today.year()
  ...
}
```

Creo que la opción uno me gusta un poquito más, porque nos permitiría definir otros valores bien conocidos que calculamos cada vez (onda, `yesterday` o `tomorrow`) y tal vez agrupar algunas definiciones sueltas como (`daysOfWeek`, `monday`, `twesday`, etc), pero si les cabe más las definiciones así podemos ir por la opción dos y olvidarnos de `yesterday` y `tomorrow`.

Diganme qué les parece y hago un PR.

**Comment by nscarcella** [comment]
Arrobo a la gilada: @fdodino @lspigariol @npasserini @PalumboN @tesonep

**Comment by fdodino** [comment]
Me gusta más la opción 1 a mí también. Hoy Wollok Xtext lo soluciona de una manera medio hackosa, me gusta que lo resolvamos desde el lenguaje.

**Comment by PalumboN** [comment]
Haciendo flush de las pestañas de Wollok que tenía abiertas llegué hasta acá y tiro tres comentarios:

- +1 a la opción 1, la opción 2 me parece desprolijo el override de una property (por más que sea const, ya sé).
- Le pondría `calendar` al objeto que se le pregunta las fechas conocidas (`today()`, `yesterday()`, ...) y esas cosas.
- **No tendría como valor default** de Date esos valores, si querés instanciar un date con new que sea diciendo los 3 componentes, sino usá el objeto calendar.

**Comment by nscarcella** [comment]
@PalumboN Por mí sí a todo eso. El único problema que veo es que tu tercer bullet no es bacguar compatibel, lo cual bien podría chuparnos un huevo, pero va a romper más ejemplos y podría herir sensibilidades.

Yo digo que desempate @fdodino y, si los dos dan el OK, hago el PR con el código.

**Comment by lspigariol** [comment]
de las opciones, me gusta mas tambien la 1

mantendria la alternativa de instanciar sin parametros, para no romper la
retrocompatibilidad en algo que no es sustancial

un detalle, que es muuuuuuuuuuuuuy improbable que pase (al menos en clase)
pero para tener en cuenta:
si ejecuto un programa desde la consola a las 23:59 de un día y hago new
Date() obtengo correctamente la fecha actual, pero si minutos despues hago
nuevamente new Date() me devuelve la misma fecha, que es la del dia
anterior!

**Comment by nscarcella** [comment]
@lspigariol 
> si ejecuto un programa desde la consola a las 23:59 de un día y hago new
Date() obtengo correctamente la fecha actual, pero si minutos despues hago
nuevamente new Date() me devuelve la misma fecha, que es la del dia
anterior!

Eso no debería pasar porque (en la variante 1) `today` es un método native y debería calcularse fresquito cada vez. La inicialización de un nuevo Date tiene que ejecutarse cada vez que hacés `new`, con lo cual había que llamar a today cada vez. 

Supongo que lo que te podría pasar es que el día cambie justo juuuuusto entre la inicialización de dos campos y cambie el mes, entonces te quedaría una fecha con el día del 31 de enero de 2022 y el més  del 1 de febrero de 2022. Si queremos cubrirnos de eso y garantizar la atomicidad no queda otra que hacerlo en un initialize:

````wollok
class Date {
  const property day = 1 // Filler. Este campo se setearía mágicamente en una native
  const property month = 1  // Filler. Este campo se setearía mágicamente en una native
  const property year = 1987  // Filler. Este campo se setearía mágicamente en una native

  method initialize() native // acá se setearían los campos a los valores posta.
  ...
}
````

Podemos llamarle a esto **Opcion 3**. Es un poco más segura pero también un poco más cochina porque estás cambiando los consts por atrás, pero podrías prescindir del objeto `today`... No sé. Como prefieran. No me queda claro si nos cuidamos de estas cosas en otros aspectos. Mientras pasen las validaciones no me importa mucho.

**Comment by fdodino** [comment]
y por qué no hacer

```wollok
class Date {
  const property day
  const property month
  const property year

  method initialize() {
    const today = calendar.today()
    const property day = today.day()
    const property month = today.month()
    const property year = today.year()
  }
  ...
}
```

Mi voto está con Lucas: mantengamos la retrocompatibilidad, sobre todo porque el cambio es casi invisible para les alumnes.

**Comment by fdodino** [comment]
aaah, creo que NicoS no quería que pudiéramos tocar los day, month e year en el initialize. Buuuuuuu!!

Entonces puedo vivir con el date.today() y que se rompa si justo lo quisiste probar 20 milisegundos antes de otro día, sos el capo de los QA, tomate una birra y volvelo a correr que en mi máquina anduvo.

**Comment by nscarcella** [comment]
> aaah, creo que NicoS no quería que pudiéramos tocar los day, month e year en el initialize. Buuuuuuu!!

No me tiren el fardo a mi, yo implementé lo que votó el comité de notables. Pero sí, ese ejemplo tiene dos problemas:
- Cambia consts en un método
- No resuelve el problema inicial: tu Date no pasa las validaciones porque lo instancias sin pasarle los consts que tiene.

Si la chance de esa diferencia les jode mucho podemos agregar una validación para detectarla en el initialize (no hace falta que sea un native) que lance un error "Felicitaciones, rompiste el Date. Intentá de nuevo". Sino, estoy con @fdodino en que no vale la pena enroñosar para un caso tan raro.

Además siempre podemos recomendar usar `today` en lugar de new Date() y listo. O sea, "deprecamos" el Date sin parámetros y lo dejamos ahí hasta que querramos volarlo como dice @PalumboN

**Comment by lspigariol** [comment]
Descartemos la opcion3. Habia visto mal el codigo (se me mezclo la opcion 1
con la 2), no hace lo que yo temía y el nuevo caso es más que raro, no vale
la pena ni mencionarlo.

**Comment by nscarcella** [comment]
Ahí creé un PR. Pasen y vean.

**Comment by fdodino** [comment]
De curioso, estás probando si se rompe Wollok Xtext?

**Comment by nscarcella** [comment]
No... No sabría cómo. Pero siéntanse libres de mandar feedback.
